insert into dbPizzeria.Ingrediente values('funghi',5,0.5);
insert into dbPizzeria.Ingrediente values('pomodori',0,0.5);
insert into dbPizzeria.Ingrediente values('salsiccia',5,0.5);
insert into dbPizzeria.Ingrediente values('uova',5,0.5);
insert into dbPizzeria.Ingrediente values('prosciutto',5,0.5);
insert into dbPizzeria.Ingrediente values('ananas',5,0.5);
insert into dbPizzeria.Pizza values('margherita',5,4.5);
insert into dbPizzeria.Pizza values('boscaiola',0,6.0);
insert into dbPizzeria.Bevanda values('peroni',0,1.5);
insert into dbPizzeria.Bevanda values('coca-cola',5,1.0);
insert into dbPizzeria.Tavolo values(3,2,null);
insert into dbPizzeria.Tavolo values(4,2,null);
call dbPizzeria.registra_cliente('1234', 'matteo', 'conti', 2);
call dbPizzeria.assegna_tavolo_a_cliente('1234', 3);
insert into dbPizzeria.scontrino (Data, ScontrinoTavolo) values(now(),3);
insert into dbPizzeria.OrdinePizza (Pizza,Tavolo) values ('margherita',3);
insert into dbPizzeria.PizzaPlus (Nome,Base) values ('margheritaFunghi','margherita');
insert into dbPizzeria.Aggiunta (PizzaPlus,Ingrediente) values ('margheritaFunghi', 'funghi');
insert into dbPizzeria.OrdinePizzaPlus (PizzaPlus,Tavolo) values ('margheritaFunghi',3);
insert into dbPizzeria.OrdineBevanda (Bevanda,Tavolo) values ('coca-cola',3);
insert into dbPizzeria.OrdineBevanda (Bevanda,Tavolo) values ('coca-cola',4);
